name: quick_mart
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: ^3.5.3

dependencies: 
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  provider: ^6.1.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  fluttertoast: ^8.2.8
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  get_storage: ^2.1.1

dev_dependencies: 
  mockito: ^5.0.16
  flutter_lints: ^4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/svg/
  fonts:
    - family: SolaimanLipi
      fonts:
        - asset: assets/fonts/SolaimanLipi_Bold.ttf
        - asset: assets/fonts/SolaimanLipi_Normal.ttf