name: quick_mart
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: ^3.5.3

dependencies: 
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  provider: ^6.1.2
  get: 4.6.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  mockito: ^5.0.16
  flutter_lints: ^4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

